# Generated by Django 2.2.28 on 2023-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDDDDDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdoop', models.BigIntegerField()),
                ('mithi', models.BigIntegerField()),
            ],
        ),
    ]
